#!/usr/bin/env bash
# World wide web

if [ $# -eq 2 ]; then
    record=$(dig $2.$1 | awk '/ANSWER SECTION/ {print $4}')
    ip=$(dig $2.$1 | awk '/ANSWER SECTION/ {print $5}')
    echo "The subdomain $2 is a $record record and points to $ip"
else
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for subdomain in ${subdomains[@]}; do
        record=$(dig $subdomain.$1 | awk '/ANSWER SECTION/ {print $4}')
        ip=$(dig $subdomain.$1 | awk '/ANSWER SECTION/ {print $5}')
        echo "The subdomain $subdomain is a $record record and points to $ip"
    done
fi
