#!/usr/bin/env bash
#When passing domain and subdomain parameters, display information for the specified subdomain

domain="$1"
sub_domain="$2"

domain_info() {
    local domain="$2"
    local sub_domain="$1"
	    record=$(dig "$sub_domain.$domain" | grep -A1 'ANSWER SECTION:')
	    type=$(echo -n "$record" | awk 'NR==2{print $4}')
	    ip=$(echo -n "$record" | awk 'NR==2{print $5}')
	    echo "The subdomain $sub_domain is a $type record and points to $ip"
	    }

if [ -z "$sub_domain" ]; then
	domain_info "www" "$domain"
	domain_info "lb-01" "$domain"
	domain_info "web-01" "$domain"
	domain_info "web-02" "$domain"
else
	domain_info "$sub_domain" "$domain"
fi