#!/usr/bin/env bash
# World wide web
dig_func () {
    domain="$1"
    subdomain="$2"
    dig "$subdomain"."$domain" +noall +answer |\
    awk -v subdomain=$subdomain '{print "The subdomain " subdomain " is a " $4 " record and points too " $5}'
}
if [ $# -eq 2 ]
then
    domain="$1"
    subdomain="$2"
    dig_func "$domain" "$subdomain"
else
    domain="$1"
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for subdomain in "${subdomains[@]}"
    do
        dig_func "$domain" "$subdomain"
    done
fi