#!/usr/bin/env bash
#commands to automatically configure a Ubuntu machine  so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '47i\    server_name _:\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;}' /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload