#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sh -c 'echo "frontend http_front
   bind *:80
   mode http
   default_backend http_back

backend http_back
   mode http
   balance roundrobin
   server 392781-web-01 100.26.252.2:80 check
   server 392781-web-02 100.25.148.5:80 check " >  /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
