#!/usr/bin/env bash
# This script print numbers from 1 to 100
i=1
while [[ i -ne 101 ]]
do
	if [[ $((i%15)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((i%3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $((i%5)) -eq 0 ]]
	then
        	echo "Buzz"
	else
		echo "$i"
    	fi
	((i++))
done
