#!/usr/bin/env bash
# task 1 but short and sweet
sed -i 's/# user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
chmod 777 /etc/nginx/nginx.conf | sudo -u nginx service nginx restart
