#!/usr/bin/env bash
# a Bash script that configures the container to fit the above requirements
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
chmod a+wrx /etc/nginx/nginx.conf | sudo -u nginx service nginx restart